"""
Django settings for mysatnusa project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import os
import environ

env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# [START] Setting DB
DB_USE = env('DB_USE')

if DB_USE == "PROD":
    DB_CONFIG = {
        "DB_HOST": "192.168.88.30",
        "DB_DATABASE": "microservices_prod",
        "DB_PORT": 5432,
        "DB_USERNAME": "dot_developer",
        "DB_PASSWORD": "4v3n93r$",
    }
else:
    DB_CONFIG = {
        "DB_HOST": "192.168.88.60",
        "DB_DATABASE": "microservices_dev",
        "DB_PORT": 5432,
        "DB_USERNAME": "dot_developer",
        "DB_PASSWORD": "Passw0rd@123",
    }
# [END] Setting DB


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['192.168.88.62', '192.168.88.60', 'localhost', '127.0.0.1']
# Change this, to when deployed to production
JWT_AUTH_EXPIRY = 12000 # in minutes, 



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_security',
    # 'example',    
    'corsheaders',
    'rest_framework',
    'drf_yasg',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mysatnusa.middleware.JsonErrorMiddleware',
    # 'django_security.middleware.ContentSecurityPolicyMiddleware',  # CSP protection
    # 'django_security.middleware.XFrameOptionsMiddleware',  # Clickjacking protection
    # 'django_security.middleware.ReferrerPolicyMiddleware',  # Referrer policy protection
]

ROOT_URLCONF = 'mysatnusa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysatnusa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# mysql
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': env('DB_DATABASE'),
#         'USER': env('DB_USERNAME'),
#         'PASSWORD': env('DB_PASSWORD'),
#         'HOST': env('DB_HOST'),
#         'PORT': env('DB_PORT'),
#         'OPTIONS': {
#             'charset': 'utf8mb4',
#         },
#     }
# }

# postgre
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_CONFIG['DB_DATABASE'],
        'USER': DB_CONFIG['DB_USERNAME'],
        'PASSWORD': DB_CONFIG['DB_PASSWORD'],
        'HOST': DB_CONFIG['DB_HOST'],
        'PORT': DB_CONFIG['DB_PORT'],
        'OPTIONS': {
            # 'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:9000",
    "http://127.0.0.1:9000",
    "http://localhost:30000",
    "http://127.0.0.1:30000",
    "http://192.168.88.60:30000",
    "http://localhost:30001",
    "http://127.0.0.1:30001",
    "http://192.168.88.60:30001",
    "http://localhost:30002",
    "http://127.0.0.1:30002",
    "http://192.168.88.60:30002",
    "http://localhost:30003",
    "http://127.0.0.1:30003",
    "http://192.168.88.60:30003",
    "http://localhost:30004",
    "http://127.0.0.1:30004",
    "http://192.168.88.60:30004",
    "http://localhost",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CORS_EXPOSE_HEADERS = ['Content-Disposition']
CORS_ALLOW_ALL_ORIGINS = True

# django_security
# SECURE_HSTS_SECONDS = 3600  # waktu dalam detik (1 jam)
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # termasuk subdomain
# SECURE_HSTS_PRELOAD = True  # preload HSTS untuk browser

# CSP_DEFAULT_SRC = ("'self'",)  # hanya mengizinkan konten dari domain sendiri

# X_FRAME_OPTIONS = 'DENY'  # mencegah semua iframe

# SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# SECURE_SSL_REDIRECT = True  # mengalihkan HTTP ke HTTPS

# SECURITY_AUDIT_LOG_ENABLED = True
# SECURITY_AUDIT_LOG_BACKEND = 'django_security.log.backends.DatabaseBackend'

APPEND_SLASH = False
